.\" man page create by R# package system.
.TH NRRD 1 2000-Jan "getRasterLayer" "getRasterLayer"
.SH NAME
getRasterLayer \- get the @\fBT:SMRUCC.DICOM.NRRD.RasterImage\fR from a specific layer in point cloud object
.SH SYNOPSIS
\fIgetRasterLayer(\fBraster\fR as <generic> RasterObject, 
\fBlayer\fR as integer);\fR
.SH DESCRIPTION
.PP
get the @\fBT:SMRUCC.DICOM.NRRD.RasterImage\fR from a specific layer in point cloud object
.PP
.SH OPTIONS
.PP
\fBraster\fB \fR\- -. 
.PP
.PP
\fBlayer\fB \fR\- the layer z-index, based 1 index. 
.PP
.SH SEE ALSO
NRRD
.SH FILES
.PP
DICOM.dll
.PP
