.\" man page create by R# package system.
.TH NRRD 1 2000-Jan "metadata" "metadata"
.SH NAME
metadata \- get nrrd header metadata
.SH SYNOPSIS
\fImetadata(\fBnrrd\fR as <generic> FileReader);\fR
.SH DESCRIPTION
.PP
get nrrd header metadata
.PP
.SH OPTIONS
.PP
\fBnrrd\fB \fR\- -. 
.PP
.SH SEE ALSO
NRRD
.SH FILES
.PP
DICOM.dll
.PP
