.\" man page create by R# package system.
.TH NRRD 1 2000-Jan "nrrdRead" "nrrdRead"
.SH NAME
nrrdRead \- open a nrrd @\fBT:SMRUCC.DICOM.NRRD.FileReader\fR
.SH SYNOPSIS
\fInrrdRead(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
open a nrrd @\fBT:SMRUCC.DICOM.NRRD.FileReader\fR
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH EXAMPLES
.PP
imports "NRRD" from "DICOM";
 
 let nrrd = NRRD::nrrdRead(file = "./test.nrrd");
.PP
.SH SEE ALSO
NRRD
.SH FILES
.PP
DICOM.dll
.PP
