.\" man page create by R# package system.
.TH NRRD 1 2000-Jan "write.nrrd_session" "write.nrrd_session"
.SH NAME
write.nrrd_session \- create a file writer session for save large raster data collection
.SH SYNOPSIS
\fIwrite.nrrd_session(\fBfile\fR as any, 
\fBdims\fR as any, 
\fBz\fR as integer = 1, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create a file writer session for save large raster data collection
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
NRRD
.SH FILES
.PP
DICOM.dll
.PP
