.\" man page create by R# package system.
.TH LASER 1 2000-Jan "as.las" "as.las"
.SH NAME
as.las \- try to cast the raw raster object to las point cloud data
.SH SYNOPSIS
\fIas.las(\fBraster\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
try to cast the raw raster object to las point cloud data
.PP
.SH OPTIONS
.PP
\fBraster\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
LASer
.SH FILES
.PP
DICOM.dll
.PP
