.\" man page create by R# package system.
.TH LASER 1 2000-Jan "open" "open"
.SH NAME
open \- Open the file read to the specific las file
.SH SYNOPSIS
\fIopen(\fBlasfile\fR as string);\fR
.SH DESCRIPTION
.PP
Open the file read to the specific las file
.PP
.SH OPTIONS
.PP
\fBlasfile\fB \fR\- -. 
.PP
.SH SEE ALSO
LASer
.SH FILES
.PP
DICOM.dll
.PP
