.\" man page create by R# package system.
.TH LASER 1 2000-Jan "points" "points"
.SH NAME
points \- load all point cloud model data
.SH SYNOPSIS
\fIpoints(\fBlas\fR as <generic> LasReader);\fR
.SH DESCRIPTION
.PP
load all point cloud model data
.PP
.SH OPTIONS
.PP
\fBlas\fB \fR\- -. 
.PP
.SH SEE ALSO
LASer
.SH FILES
.PP
DICOM.dll
.PP
