.\" man page create by R# package system.
.TH LASER 1 2000-Jan "write.las" "write.las"
.SH NAME
write.las \- 
.SH SYNOPSIS
\fIwrite.las(\fBraster\fR as any, 
\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBraster\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- 
 the format version of the las file is 1.2, and
 the point data format is 2(RGB) value
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
LASer
.SH FILES
.PP
DICOM.dll
.PP
